/* main.c
 *
 * Copyright (C) 2026 wolfSSL Inc.
 *
 * This file is part of wolfTrust.
 *
 * wolfTrust is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfTrust is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <https://www.gnu.org/licenses/>.
 */

/* WT-PORT-0020 (bootloader record path): a record built by
 * tools/handoff/mkhandoff.py is consumed through the port accessor, its
 * source is cleared, and every corrupted or short record is refused and
 * zeroed. */

#include "wolftrust/boot_handoff.h"
#include "wolftrust/platform.h"
#include "wolftrust/arch.h"
#include "wolftrust/static_assert.h"

#include <stddef.h>
#include <stdio.h>
#include <string.h>

#define REGION_SIZE 64u

WT_STATIC_ASSERT(sizeof(wt_boot_handoff_t) == 56u, "record is 56 bytes");
WT_STATIC_ASSERT(offsetof(wt_boot_handoff_t, magic) == 0u, "magic offset");
WT_STATIC_ASSERT(offsetof(wt_boot_handoff_t, magic_inverse) == 4u,
               "magic_inverse offset");
WT_STATIC_ASSERT(offsetof(wt_boot_handoff_t, version) == 8u, "version offset");
WT_STATIC_ASSERT(offsetof(wt_boot_handoff_t, size) == 10u, "size offset");
WT_STATIC_ASSERT(offsetof(wt_boot_handoff_t, lifecycle) == 12u,
               "lifecycle offset");
WT_STATIC_ASSERT(offsetof(wt_boot_handoff_t, image_version) == 16u,
               "image_version offset");
WT_STATIC_ASSERT(offsetof(wt_boot_handoff_t, hash_algorithm) == 20u,
               "hash_algorithm offset");
WT_STATIC_ASSERT(offsetof(wt_boot_handoff_t, measurement_size) == 22u,
               "measurement_size offset");
WT_STATIC_ASSERT(offsetof(wt_boot_handoff_t, measurement) == 24u,
               "measurement offset");

static uint8_t g_region[REGION_SIZE];
static size_t g_region_size = REGION_SIZE;
static int g_region_null;
static int checks;
static int failures;

volatile void* wt_platform_boot_handoff_region(size_t* size)
{
    if (size != NULL) {
        *size = g_region_size;
    }
    if (g_region_null) {
        return NULL;
    }
    return g_region;
}

void wt_arch_dmb(void)
{
}

void wt_arch_dsb(void)
{
}

static void check(int ok, const char* what)
{
    checks++;
    if (ok) {
        printf("  [check] PASS  %s\n", what);
    }
    else {
        failures++;
        printf("  [check] FAIL  %s\n", what);
    }
}

static int load_record(const char* path)
{
    FILE* file;
    size_t got;

    memset(g_region, 0xA5, sizeof(g_region));
    file = fopen(path, "rb");
    if (file == NULL) {
        return -1;
    }
    got = fread(g_region, 1u, sizeof(wt_boot_handoff_t), file);
    fclose(file);
    return (got == sizeof(wt_boot_handoff_t)) ? 0 : -1;
}

static int region_cleared(void)
{
    size_t i;

    for (i = 0u; i < sizeof(wt_boot_handoff_t); ++i) {
        if (g_region[i] != 0u) {
            return 0;
        }
    }
    return 1;
}

static int region_all_zero(void)
{
    size_t i;

    for (i = 0u; i < sizeof(g_region); ++i) {
        if (g_region[i] != 0u) {
            return 0;
        }
    }
    return 1;
}

static int output_zeroed(const wt_boot_handoff_t* handoff)
{
    const uint8_t* bytes = (const uint8_t*)handoff;
    size_t i;

    for (i = 0u; i < sizeof(*handoff); ++i) {
        if (bytes[i] != 0u) {
            return 0;
        }
    }
    return 1;
}

static void expect_refused(const char* path, size_t offset, const char* what)
{
    wt_boot_handoff_t out;
    int rc;

    if (load_record(path) != 0) {
        check(0, what);
        return;
    }
    g_region[offset] ^= 0x01u;
    memset(&out, 0xC3, sizeof(out));
    rc = wt_boot_handoff_consume(&out);
    check((rc != 0) && output_zeroed(&out) && region_cleared(), what);
}

int main(int argc, char** argv)
{
    wt_boot_handoff_t out;
    uint8_t expected[WT_BOOT_HANDOFF_DIGEST_SIZE];
    const char* path;
    size_t i;
    int rc;

    if (argc < 2) {
        fprintf(stderr, "usage: %s <handoff.bin>\n", argv[0]);
        return 2;
    }
    path = argv[1];
    for (i = 0u; i < sizeof(expected); ++i) {
        expected[i] = (uint8_t)i;
    }

    printf("WT-PORT-0020 (bootloader record path)\n");
    check(load_record(path) == 0, "record generated by mkhandoff.py loads");
    memset(&out, 0xC3, sizeof(out));
    rc = wt_boot_handoff_consume(&out);
    check(rc == 0, "consume accepts the generated record");
    check((out.magic == WT_BOOT_HANDOFF_MAGIC) &&
          (out.magic_inverse == ~WT_BOOT_HANDOFF_MAGIC), "magic pair");
    check((out.version == WT_BOOT_HANDOFF_VERSION) &&
          (out.size == sizeof(out)), "version and size");
    check((out.hash_algorithm == WT_BOOT_HANDOFF_HASH_SHA256) &&
          (out.measurement_size == WT_BOOT_HANDOFF_DIGEST_SIZE),
          "hash algorithm and digest size");
    check(out.lifecycle == 0x3000u, "lifecycle SECURED (0x3000)");
    check(out.image_version == 7u, "image version 7");
    check(memcmp(out.measurement, expected, sizeof(expected)) == 0,
          "measurement bytes");
    check(region_cleared(), "source region cleared after consume");

    memset(&out, 0xC3, sizeof(out));
    rc = wt_boot_handoff_consume(&out);
    check((rc != 0) && output_zeroed(&out),
          "replay of the cleared region refused");

    expect_refused(path, 0u, "corrupt magic refused and zeroed");
    expect_refused(path, 4u, "corrupt magic inverse refused and zeroed");
    expect_refused(path, 8u, "corrupt version refused and zeroed");
    expect_refused(path, 10u, "corrupt size refused and zeroed");
    expect_refused(path, 20u, "corrupt hash algorithm refused and zeroed");
    expect_refused(path, 22u, "corrupt measurement size refused and zeroed");

    check(load_record(path) == 0, "reload for the short-region case");
    g_region_size = sizeof(wt_boot_handoff_t) - 1u;
    memset(&out, 0xC3, sizeof(out));
    rc = wt_boot_handoff_consume(&out);
    check((rc != 0) && output_zeroed(&out),
          "region shorter than the record refused and zeroed");
    g_region_size = REGION_SIZE;

    check(wt_boot_handoff_consume(NULL) != 0, "NULL output refused");

    /* Boot-cleanup contract (wt_boot_handoff_clear): zero a present region, and
     * be a safe no-op when the port reports no handoff region. The absent case
     * pairs a NULL pointer with a nonzero size; reaching the next check without
     * a fault (caught hard under ASan/Valgrind) is the assertion. */
    g_region_null = 0;
    g_region_size = REGION_SIZE;
    memset(g_region, 0xA5, sizeof(g_region));
    wt_boot_handoff_clear();
    check(region_all_zero(), "clear zeroes a present handoff region");

    g_region_null = 1;
    g_region_size = REGION_SIZE;
    wt_boot_handoff_clear();
    check(1, "clear is a safe no-op when the region is absent (NULL, nonzero size)");
    g_region_null = 0;

    printf("boot_handoff: %d checks, %d failures\n", checks, failures);
    return (failures == 0) ? 0 : 1;
}
