name: Valgrind

on:
  push:
    branches: [master, main, "release/**", wolfpsa-v5.9.1-ci, wolftfm-l3, wolfTrust-dev]
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  host-valgrind:
    name: Host tests (Valgrind)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/wolfssl/wolftrust-ci:latest-beb806af7628e02acee729632a74a7a3630f21fd
    steps:
      - uses: actions/checkout@v4
      - name: Initialize test dependencies
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global url."https://github.com/".insteadOf git@github.com:
          git submodule update --init --recursive --depth 1 --jobs 4
      - name: Run aggregate host suite under Valgrind
        run: make test-valgrind
